name: Conformance Tests

on:
  push:
    branches:
      - '**'
  pull_request:
  # TODO: add cron

jobs:
  conformance:
    strategy:
      max-parallel: 1
      matrix:
        java-version: [11, 17]
        sigstore-env: [production, staging]
      fail-fast: false

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@94baf225fe0a508e581a564467443d0e2379123b # v4.3.0

      - name: Build sigstore-java cli
        run: ./gradlew :sigstore-cli:build

      - name: Unpack sigstore-java distribution
        run: tar -xvf ${{ github.workspace }}/sigstore-cli/build/distributions/sigstore-cli-*.tar --strip-components 1

      - uses: sigstore/sigstore-conformance@640e7dfb715518eeeb492910c6d244cedcc6cfea # v0.0.17
        with:
          entrypoint: ${{ github.workspace }}/bin/sigstore-cli
          environment: ${{ matrix.sigstore-env }}
          xfail: "test_verify_dsse_bundle_with_trust_root"
