name: Conformance Tests

on:
  push:
    branches: [main]
  pull_request: {}
  # TODO: add cron

jobs:
  conformance:
    strategy:
      max-parallel: 1
      matrix:
        java-version: [11, 17]
        sigstore-env: [production, staging]
      fail-fast: false

    concurrency:
      # On main/release, we don't want any jobs cancelled
      # On PR branches, we cancel the job if new commits are pushed
      # More info: https://stackoverflow.com/a/70972844/1261287
      group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}-${{ matrix.java-version }}-${{ matrix.sigstore-env }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Set up JDK 17
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@ac638b010cf58a27ee6c972d7336334ccaf61c96 # v4.4.1

      - name: Build sigstore-java cli
        run: ./gradlew :sigstore-cli:build

      - name: Unpack sigstore-java distribution
        run: tar -xvf ${{ github.workspace }}/sigstore-cli/build/distributions/sigstore-cli-*.tar --strip-components 1

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - uses: sigstore/sigstore-conformance@fd90e6b0f3046f2276a6659481de6df495dea3b9 # v0.0.18
        with:
          entrypoint: ${{ github.workspace }}/bin/sigstore-cli
          environment: ${{ matrix.sigstore-env }}
          xfail: "test_verify_dsse_bundle_with_trust_root"
